print("hello friend, i am learning python")
print( " hello Mr. Martins")
print("how are you coping with your new task?")
print("hope to see you soon")
name=("susan")
print(name)
print("my name is" +" "+ name)
print("what is your name?")
print(f"hello {name}")
